name: Deploy to server

on: push

jobs:
  primer_job:
    runs-on: ubuntu-latest

    env:
      NAME: TadeoPortela

    steps:
      - name: Exportar Variable
        id: step_1
        run: echo "mi_variable=Hola Mundo" >> GITHUB_OUTPU

      - name: Importar Variable Step
        run: echo "${{ steps.step_1.outputs.mi_variable }}"

      - name: Action
        uses: actions/checkout@v4

      - name: DespuesAcccion
        run: ls -al

  segundo_job:
    needs: primer_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo 2
        run: echo "hola mundo 2 ${{ github.ref}}"
