name: Deploy to server

on: push

jobs:
  primer_job:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.mi_variable }}

    steps:
      - name: Generar archivo
        run: |
          echo "archivo de prueba, hola" >> test.log

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log

  segundo_job:
    runs-on: ubuntu-latest
    needs: primer_job

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: Cat file
        run: cat test.log
