name: Deploy to server

on: push

jobs:
  primer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout

  segundo_job:
    if: false
    needs: primer_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo 2
        run: echo "hola mundo 2 ${{ github.ref}}"
