name: Deploy to server

on: push

jobs:
  primer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "hola mundo"

  segundo_job:
    needs: primer_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo 2
        run: echo "hola mundo 2"
