name: Deploy to server

on: push

jobs:
  primer_job:
    runs-on: ubuntu-latest

    env:
      NAME: TadeoPortela

    steps:
      - name: Working dir
        run: echo $GITHUB_OUTPUT

      - name: VariableEntorno
        run: echo "Mi nombre es $NAME"

      - name: Action
        uses: actions/checkout@v4

      - name: DespuesAcccion
        run: ls -al

  segundo_job:
    needs: primer_job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo 2
        run: echo "hola mundo 2 ${{ github.ref}}"
